from math import *
import math

print ("Zero is", int(4+4-4-4))
print ("One is", int(4/4+4-4))
print ("Two is", int(4/4+4/4))
print ("Three is", int((4+4+4)/4))
print ("Five is", int((4 * 4 + 4) / 4))
print ("Six is", int(4+(4+4)/4))
print ("Seven is",int( ((4*4-sqrt(4))/sqrt(4))))
print ("Eight is", int(4*(4+4)/4))
print ("Nine is",int( 4+4+4/4))
print ("Ten is", int(4+sqrt(4)+(sqrt(4)+sqrt(4))))
print ("Eleven is", int(math.factorial(4)/sqrt(4)-(4/4)))
print ("Twelve is", int(4*(sqrt(4)+sqrt(4))-4))
print ("Thirteen is", int(math.factorial(4)/sqrt(4)+(4/4)))
print ("Fourteen is", int(4*4-(4/sqrt(4))))
print ("Fifteen is", int((4*4-(sqrt(4))/sqrt(4))))
print ("Sixteen is", int(4*4/(4/4)))
print ("Seventeen is", int(4*4+(4/4)))
print ("Eighteen is", int(4*4+(4/sqrt(4))))
print ("Nineteen is", int(math.factorial(4)-(4+(4/4))))
print ("Twenty is", int(4*(4/4+4)))

#print ("Twenty one is", int(math.factorial(4)-4+(4/4)))
#print ("Twenty two is", int(math.factorial(4)-4+(4/sqrt(4))))
#print ("Twenty three is", int(math.factorial(4)-4+(4/sqrt(4))))
